### ISSUE TITLE
Issue 713 in android-scripting: sl4a is not working with Android 5.1

### ISSUE THREAD

**Issue by kuri65536** [kuri65536/sl4a#1]
* What device(s) are you experiencing the problem on? 
  * Lollipop device
* What firmware version are you running on the device? 
  * Andriod 5.1
* What steps will reproduce the problem?
  1.sl4a and pythonfor andriod apk's are installed.
  2.If i try to run python script blank screen is coming up and keyboard is  appearing.
  3.In the notification window it shows script is running but nothing is  working

* What is the expected output? What do you see instead?
  * The python script should execute.

* What version of the product are you using? On what operating system?
  * Andriod 5.1

Please provide any additional information below.

**Comment by kuri65536** [comment]
I confirmed with the python2 and latest "Android 5.1 armeabi-v7a".

- launch interpreter = OK
- launch hello world (toast example) = OK

Please **remove** and install SL4A and python-for-android.

**Comment by 66eli77** [comment]
you mean it works for Android 5.1 now? 
I'm using android-python27(it really is a SL4A apk), which won't work on Lollipop : (

**Comment by kuri65536** [comment]
I confirmed to run SL4A in above emulators (not real devices),
and I think there are no reasons to fail SL4A in real devices.
Please give me more informations like SL4A logcat output or python error messages.
* arm API22(5.1) image
* x86 API22(5.1) image

**Comment by kuri65536** [comment]
I got information from py4a users that SL4A work with Lollipop.

* Galaxy S6
* Sony Xperia M

**Comment by ainsophical** [comment]
@66eli77 i forked android-python27 and added the PIE executables. Its working on 5.0 and beyond now.

**Comment by Ismael-VC** [comment]
>  i forked android-python27 and added the PIE executables.

@ainsophical is there someplace that documents this step? I'm sorry I'm not an expert on this, by PIE do you mean?

* https://en.wikipedia.org/wiki/Position-independent_code

**Comment by Ismael-VC** [comment]
I only get this using the latest APK:

* https://github.com/kuri65536/sl4a/releases

I can't seem to do anything:

 ![12788224_1690412091248328_1017446529_n](https://cloud.githubusercontent.com/assets/4594825/13441602/b4dca0d0-dfbd-11e5-89d5-864f7bb1f7d3.jpg)

Cellphone specs:

![12803973_1690412264581644_1746453289_n](https://cloud.githubusercontent.com/assets/4594825/13441605/b80cce06-dfbd-11e5-9290-6ec39c44bfb6.jpg)
![12784638_1690412297914974_430212703_n](https://cloud.githubusercontent.com/assets/4594825/13441608/badb542c-dfbd-11e5-8019-062b13df1b7b.jpg)

**Comment by ainsophical** [comment]
im really not working on the sl4a project per se. I am modifying it to work in conjunction with android-python27 project which i forked ---> https://github.com/ainsophical/droid-python

PIE = position independent executable. at 5.0 google force all executables to be PIE.

in your case, long press your menu button to get a menu. you should get your options to go to interpreter, scripts, etc. or try to swipe left or right...

i had a problem figuring that out when they got rid of the standard menu button on android. in order to use menus through the old style way you have to long press now...

**Comment by kuri65536** [comment]
PIE binary already hosted in my project "python-for-android" from last year.

**Comment by ainsophical** [comment]
thanks for compiling those. i was at a lost when i started working with the 'android-python27' project. it would work on my 4.4.2 device but not my 5.0. after some research found out about the strict PIE policy for 5.0 and greater. I forked the project, added those binaries, fixed some EPERM errors, and it's working again. I have been working on a idea that runs bottle and uses webview for the interface and it works out pretty good. the problem right now is if i target any higher sdk in gradle, my sl4a calls break because the java methods through webview need to annotated with @javascriptinterface after api 17. im interested in fixing that and i like your ideas about adding new facades to sl4a. great work keeping sl4a alive.

**Comment by kuri65536** [comment]
@Ismael-VC 
SL4A is just the environment for languages,
please install language apk like python-for-android or the others.
https://github.com/kuri65536/python-for-android/releases
